### ISSUE TITLE
error in anvi-load-sqm.py

### ISSUE THREAD

**Issue by bresyd** [jtamames/SqueezeMeta#105]
Hi guys,

sorry to bother you again. After successfully solving my last issue with your help (issue #102) my SQM run finished without further issues. I am now aiming to load my results into anvio using `anvi-load-sqm.py`; since my dataset is quite large I thought I first test the script on the Hadza test run and I got the following error:
```
                                                                                              [01 Jun 20 11:22:34 Init] Reading BAM File              
✖ anvi-profile encountered an error after 0:00:12.883954
Traceback (most recent call last):
  File "/home/btschits/miniconda3/envs/anvio-6.2/bin/anvi-profile", line 93, in <module>
    main(args)
  File "/home/btschits/miniconda3/envs/anvio-6.2/lib/python3.6/site-packages/anvio/terminal.py", line 748, in wrapper
    program_method(*args, **kwargs)
  File "/home/btschits/miniconda3/envs/anvio-6.2/bin/anvi-profile", line 33, in main
    profiler.BAMProfiler(args)._run()
  File "/home/btschits/miniconda3/envs/anvio-6.2/lib/python3.6/site-packages/anvio/profiler.py", line 267, in _run
    self.init_profile_from_BAM()
  File "/home/btschits/miniconda3/envs/anvio-6.2/lib/python3.6/site-packages/anvio/profiler.py", line 443, in init_profile_from_BAM
    self.bam = bamops.BAMFileObject(self.input_file_path)
  File "pysam/libcalignmentfile.pyx", line 741, in pysam.libcalignmentfile.AlignmentFile.__cinit__
  File "pysam/libcalignmentfile.pyx", line 990, in pysam.libcalignmentfile.AlignmentFile._open
ValueError: file has no sequences defined (mode='r') - is it SAM/BAM format? Consider opening with check_sq=False
Traceback (most recent call last):
  File "/home/btschits/miniconda3/envs/SqueezeMeta/SqueezeMeta/utils/anvio_utils/anvi-load-sqm.py", line 334, in <module>
    main(parse_arguments())
  File "/home/btschits/miniconda3/envs/SqueezeMeta/SqueezeMeta/utils/anvio_utils/anvi-load-sqm.py", line 315, in main
    create_profileDB(args.project, args.output, args.min_contig_length, args.min_mean_coverage, args.num_threads, args.skip_SNV_profiling, args.profile_SCVs, version)
  File "/home/btschits/miniconda3/envs/SqueezeMeta/SqueezeMeta/utils/anvio_utils/anvi-load-sqm.py", line 225, in create_profileDB
    run_command(command_base)
  File "/home/btschits/miniconda3/envs/SqueezeMeta/SqueezeMeta/utils/anvio_utils/anvi-load-sqm.py", line 88, in run_command
    print('There must be some problem with "{}".\nIt\'s better to stop and check it'.format(' '.join(command)))
TypeError: sequence item 8: expected str instance, int found
```
Any ideas about what could be going wrong here? Could this issue maybe again be related to my linux debian? Or is it not even a SQM error but instead an anvio issue?

Thanks a lot for your help

**Comment by ggnatalia** [comment]
Hi,

The main error occurs in anvio, however it seems to be related to the sam/bam files.  I'm trying to reproduce your error, but until then, could you run:

    head <project_name>.sam

    tail  <project_name>.sam

and send the output? It is to check that your sam files (they are in the data/sam directory) are not empty. 

Additionally, when you run anvi-load-sqm, in your results directory, a folder called sqm2anvio should have been created. Could you run:

    ls -ltr sqm2anvio/bam/

to be sure that the bam files are not empty?

I hope to give you a better answer soon.

Best,
Natalia

**Comment by ggnatalia** [comment]
Thanks for sending the output. We have identified the bug.

Your bam files are empty:

    -rw-r--r-- 1 btschits biogeo  0 Jun  1 11:09 SRR1927149-RAW.bam
    -rw-r--r-- 1 btschits biogeo  0 Jun  1 11:09 SRR1929485-RAW.bam

But there are no warnings until anvio try to use them and they are empty (we solve it in future versions).

This is due to the binary of samtools that we distribute is not working in your debian distribution.

Could you download the samtools (https://github.com/samtools/samtools/releases) (the tar.bz2 file), compile it, and put the binary in the SqueezeMeta/bin directory (replacing the old one)?

We use the 1.9 version, but I hope it works well with the 1.10 version, which is recent. Hopefully, the problem will be solved.


Please inform us if it works and if you find other issues.

**Comment by jtamames** [comment]
Closing by inactivity
