### ISSUE TITLE
Java error in 02.run_barrnap.pl

### ISSUE THREAD

**Issue by michoug** [jtamames/SqueezeMeta#13]
Hi,
When running the Test script, I got this error

```
Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/commons/io/output/NullWriter
	at edu.msu.cme.rdp.classifier.cli.ClassifierMain.main(ClassifierMain.java:67)
Caused by: java.lang.ClassNotFoundException: org.apache.commons.io.output.NullWriter
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 1 more
Error running command:    java -jar /home/michoug/SqueezeMeta/scripts/../bin/classifier.jar classify /ibex/scratch/michoug/Test/Hadza/temp/16S.fasta -o /ibex/scratch/michoug/Test/Hadza/temp/16S.out -f filterbyconf at /home/michoug/SqueezeMeta/scripts/../scripts/02.run_barrnap.pl line 119.
Stopping in STEP2 -> 02.run_barrnap.pl
```

Any ideas ?

**Comment by fpusan** [comment]
Hi!
What is your OS and java version? Are you running SqueezeMeta in a cluster?

This issue in the RDP classifier has actually been reported previously in their website (https://github.com/rdpstaff/RDPTools/issues/8) and originates from missing java libraries. We ship those with SqueezeMeta, so in theory there should be no problem.

Can you check whether the files
```
AlignmentTools.jar
ReadSeq.jar
TaxonomyTree.jar
commons-cli-1.2.jar
commons-io-2.4.jar
jcommon-1.0.16.jar
jfreechart-1.0.13.jar
```
are present in the SqueezeMeta/lib/classifier/lib directory?

**Comment by michoug** [comment]
Hi, yes it's a cluster and yes the files are present in the directory

**Comment by fpusan** [comment]
And the OS version?

**Comment by michoug** [comment]
Hi, sorry forgot, the OS is CentOS Linux release 7.5.1804

**Comment by fpusan** [comment]
Sorry, I also forgot to ask again, what is the java version?

Can you run the same command

`java -jar /home/michoug/SqueezeMeta/scripts/../bin/classifier.jar classify /ibex/scratch/michoug/Test/Hadza/temp/16S.fasta -o /ibex/scratch/michoug/Test/Hadza/temp/16S.out -f filterbyconf`

in the frontend node and see if it also fails?

**Comment by michoug** [comment]
The java version is 

```
java version "9.0.1"
Java(TM) SE Runtime Environment (build 9.0.1+11)
Java HotSpot(TM) 64-Bit Server VM (build 9.0.1+11, mixed mode)
```

It also fails in the frontend node

**Comment by fpusan** [comment]
I can't reproduce after installing java 9.0.1 in my CentOS (7.6.1810) VM.

What happens when you run 
`java -jar /home/michoug/SqueezeMeta/lib/classifier/classifier.jar classify /ibex/scratch/michoug/Test/Hadza/temp/16S.fasta -o /ibex/scratch/michoug/Test/Hadza/temp/16S.out -f filterbyconf`

in the frontend?

**Comment by fpusan** [comment]
Closed. No activity, can't reproduce
