### ISSUE TITLE
SQMtools error cannot open file  '...bin.tax.tsv': No such file or directory

### ISSUE THREAD

**Issue by fconstancias** [jtamames/SqueezeMeta#192]
Dear SqueezMeta developpers,

Related to my [previous post ](https://github.com/jtamames/SqueezeMeta/issues/190), I would like to extract functionmal gene annotation for the different bins.

When trying to loadSQM I encounter the following error:
```
(SqueezeMetaConda200817) R
library('SQMtools')
packageVersion('SQMtools')
[1] ‘0.5.0’
SM = loadSQM('HS-3CA-MESO', engine = 'data.table')
Loading orfs
    table...
|--------------------------------------------------|
|==================================================|
    abundances...
    sequences
|--------------------------------------------------|
|==================================================|
    taxonomy...
|--------------------------------------------------|
|==================================================|
Loading contigs
    table...
    abundances...
    sequences...
|--------------------------------------------------|
|==================================================|
    taxonomy...
    binning info...
Loading bins
    table...
    abundances...
    taxonomy...
Error in file(file, "rt") : cannot open the connection
In addition: Warning message:
In file(file, "rt") :
  cannot open file 'HS-3CA-MESO/results/tables/HS-3CA-MESO.bin.tax.tsv': No such file or directory
```

It seems the HS-3CA-MESO.bin.tax.tsv is actually HS-3CA-MESO.orf.tax.nofilter.tsv 
```
ls HS-3CA-MESO/results/tables/
HS-3CA-MESO.class.allfilter.abund.tsv    HS-3CA-MESO.genus.prokfilter.abund.tsv  HS-3CA-MESO.PFAM.abund.tsv
HS-3CA-MESO.class.prokfilter.abund.tsv   HS-3CA-MESO.KO.abund.tsv                HS-3CA-MESO.PFAM.bases.tsv
HS-3CA-MESO.COG.abund.tsv                HS-3CA-MESO.KO.bases.tsv                HS-3CA-MESO.PFAM.copyNumber.tsv
HS-3CA-MESO.COG.bases.tsv                HS-3CA-MESO.KO.copyNumber.tsv           HS-3CA-MESO.PFAM.tpm.tsv
HS-3CA-MESO.COG.copyNumber.tsv           HS-3CA-MESO.KO.names.tsv                HS-3CA-MESO.phylum.allfilter.abund.tsv
HS-3CA-MESO.COG.names.tsv                HS-3CA-MESO.KO.tpm.tsv                  HS-3CA-MESO.phylum.prokfilter.abund.tsv
HS-3CA-MESO.COG.tpm.tsv                  HS-3CA-MESO.order.allfilter.abund.tsv   HS-3CA-MESO.RecA.tsv
HS-3CA-MESO.contig.sequences.tsv         HS-3CA-MESO.order.prokfilter.abund.tsv  HS-3CA-MESO.species.allfilter.abund.tsv
HS-3CA-MESO.contig.tax.tsv               HS-3CA-MESO.orf.sequences.tsv           HS-3CA-MESO.species.prokfilter.abund.tsv
HS-3CA-MESO.family.allfilter.abund.tsv   HS-3CA-MESO.orf.tax.allfilter.tsv       HS-3CA-MESO.superkingdom.allfilter.abund.tsv
HS-3CA-MESO.family.prokfilter.abund.tsv  HS-3CA-MESO.orf.tax.nofilter.tsv        HS-3CA-MESO.superkingdom.prokfilter.abund.tsv
HS-3CA-MESO.genus.allfilter.abund.tsv    HS-3CA-MESO.orf.tax.prokfilter.tsv
```

Is there anything I am missing here?

Best,

Florentin

**Comment by fpusan** [comment]
The `HS-3CA-MESO.bin.tax.tsv` file should be there. Maybe the tables were generated with an older version of the `sqm2tables.py` script?

To make sure, I would update to the latest version, then remove the `HS-3CA-MESO/results/tables/` and try to load it again into SQMtools (again, using the latest SQMtools, which is 0.6.0, although conda should take care of everything for you).

Let me know if this fixes it, if not I might ask you for your data so I can try to reproduce the bug in my server.

**Comment by fconstancias** [comment]
> Maybe the tables were generated with an older version of the sqm2tables.py script?
Yes, highly probable. I run first without the binning and then performed binning with possibly an updated conda install. Any idea how could I investigate more that point?

I removed the `HS-3CA-MESO/results/tables/` but got another error.
```
> SM = loadSQM('HS-3CA-MESO', engine= 'data.table')
Generating tabular outputs for project in HS-3CA-MESO

Loading orfs
    table...
|--------------------------------------------------|
|==================================================|
    abundances...
    sequences
|--------------------------------------------------|
|==================================================|
    taxonomy...
|--------------------------------------------------|
|==================================================|
Loading contigs
    table...
    abundances...
    sequences...
|--------------------------------------------------|
|==================================================|
    taxonomy...
    binning info...
Loading bins
    table...
    abundances...
    taxonomy...
Loading taxonomies
Loading functions
Error in file(file, "rt") : cannot open the connection
In addition: Warning message:
In file(file, "rt") :
  cannot open file 'HS-3CA-MESO/results/tables/HS-3CA-MESO.KO.cov.tsv': No such file or directory
> 
> library('SQMtools')
> packageVersion('SQMtools')
[1] ‘0.6.0’
```

**Comment by fpusan** [comment]
My bad, I think.
Try removing the directory again and creating it manually with
`sqm2tables.py HS-3CA-MESO HS-3CA-MESO/results/tables/` 
then try to load it in SQMtools again. Make sure you use the latest version of `sqm2tables.py`.

**Comment by fconstancias** [comment]
Tried already with the version installed on 01/11/2020, :-( 
```
(SqueezeMeta201101) constancias@scelse:/datadrive02/Flo/HS$ sqm2tables.py HS-3CA-MESO HS-3CA-MESO/results/tables/
Traceback (most recent call last):
  File "/home/constancias/miniconda3/envs/SqueezeMeta201101/bin/sqm2tables.py", line 195, in <module>
    main(parse_args())
  File "/home/constancias/miniconda3/envs/SqueezeMeta201101/bin/sqm2tables.py", line 58, in main
    total_reads, total_bases = parse_mappingstat(perlVars['$mappingstat'])
KeyError: '$mappingstat'
```

**Comment by fpusan** [comment]
No problem. Backwards compatibility is not our forte.
Edit the `SqueezeMeta_conf.pl` file inside the project's directory.
Below line 55 add the following:
`$mappingstat     = "$resultpath/10.$projectname.mappingstat";`
Save and run sqm2tables again. It should work

**Comment by fconstancias** [comment]
worked perfectly, thanks !
