### ISSUE TITLE
anvi-load-sqm.py error

### ISSUE THREAD

**Issue by fconstancias** [jtamames/SqueezeMeta#194]
I am encountering an error using `anvi-load-sqm.py` since I updated SqueezeMeata. It seems anvi-load-sqm.py  required an anvio conda environment named `6.2-master`. Is that correct?
```
(anvio-6.2)$ python3 /home/constancias/miniconda3/envs/SqueezeMeta201101/SqueezeMeta/utils/anvio_utils/anvi-load-sqm.py -p SM-EZ-exp1 -o SM-EZ-exp1/anvio --num-threads 20 --run-HMMS --run-scg-taxonomy --profile-SCVs --min-contig-length 1000
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Loading results from SQM in anvi'o.
Anvi'o is an advanced analysis and visualization platform for 'omics data.
Citation: Eren AM, Ozcan E, Quince C, Vineis JH, Morrison HG, Sogin ML, Delmont TO. (2015) Anvi'o: an advanced analysis and visualization platform for 'omics data. PeerJ 3:e1319
This script calls to sqm2anvio.pl and then runs a set of pre-defined commands to create an anvio database.
If you want to explore ways to manually create the database, and other cool stuff that you can do with anvi'o
please consider checking the anvi'o project page for information, tutorials and more details (http://merenlab.org/software/anvio/).
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/constancias/miniconda3/envs/SqueezeMeta201101/SqueezeMeta/utils/anvio_utils/anvi-load-sqm.py", line 423, in <module>
    main(parse_arguments())
  File "/home/constancias/miniconda3/envs/SqueezeMeta201101/SqueezeMeta/utils/anvio_utils/anvi-load-sqm.py", line 383, in main
    version = float(anvio.__version__)
ValueError: could not convert string to float: '6.2-master'
```

**Comment by fpusan** [comment]
I think that we are expecting the version string to be just "6.2". So far it has worked for us, what we use to do is install anvi'o on top of the SqueezeMeta conda environment (e.g. `conda install -y -c conda-forge -c bioconda anvio==6.2`) . Maybe they have recently change how they name their versions. Anyways, we should fix that on our part (@ggnatalia, that's up your alley). Meanwhile you can use an older anvio version (I think 6.1 worked fine in our tests).

**Comment by ggnatalia** [comment]
Hi,

How have you installed anvio?

I’ve just installed the stable version of anvio (Installation with conda: Installation for Linux / Windows users: http://merenlab.org/2016/06/26/installation-v2/#installation-with-conda-painless-method-suggested-for-everyone) and everything worked ok. For your error message it seems that you have installed the anvio master version from their github repo. That's perfect to have the latest updates of anvio but it could be less stable. 

We only support stable anvi’o versions through conda, and their latest official release is anvio-6.2. To sum up, your version is not the official release of 6.2, is an improved version that, hopefully, will be a stable 6.3 anvi’o version in the future (and we’ll support it when it gets published). 

Meanwhile, you can install the stable release 6.2 from conda and the script should work ok (if it doesn't, please tell us).

**Comment by fpusan** [comment]
Closing due to lack of activity, we'll give support to the new v7.0 of anvi'o in our next release.
