### ISSUE TITLE
Sequenctial mode with external assembly

### ISSUE THREAD

**Issue by fconstancias** [jtamames/SqueezeMeta#266]
Dear SqueexeMeta team,

Thanks again for your amazing tool.

I am trying to perform the sequential mode providing an external assembly and I am only interested in binning.

I have used the following command which I looped:
`
SqueezeMeta.pl -m coassembly -contiglen 1000 --nocog --nokegg --nopfam -p ${SAMPLE} -s ${SAMPLE}.txt -f DNA_RNA/ -extassembly ${SAMPLE}_contigs.fasta -b 60 -t ${NSLOTS}`

Is it correct? 

Thanks for your support.

Best

**Comment by jtamames** [comment]
Hello!

I think it is easier if you add the `-extassembly ` option in the samples file directly. You can specify a different external assembly for each sample, is that what you want? And in that way you just need to run it in sequential mode. See page 9 in the manual for the specification of this in the samples file.

Best,
Javier

**Comment by fconstancias** [comment]
Thanks, I should have checked the manual!

**Comment by fconstancias** [comment]
I actually got the following error:
```
Running DAS Tool for maxbin,metabat2: LD_LIBRARY_PATH=/home/constancias/miniconda3/envs/SqueezeMeta160321/SqueezeMeta/lib PATH=/home/constancias/miniconda3/envs/SqueezeMeta160321/SqueezeMeta/bin:$PATH /home/constancias/miniconda3/envs/SqueezeMeta160321/SqueezeMeta/bin/DAS_Tool/DAS_Tool -i /datadrive05/Flo/Saliva/Saliva2/squeezemeta/squ
eezmeta_4thstrategy/K9_SALIVA_DNA/results/DAS/maxbin.table,/datadrive05/Flo/Saliva/Saliva2/squeezemeta/squeezmeta_4thstrategy/K9_SALIVA_DNA/results/DAS/metabat2.table -l maxbin,metabat2 -c /datadrive05/Flo/Saliva/Saliva2/squeezemeta/squeezmeta_4thstrategy/K9_SALIVA_DNA/results/01.K9_SALIVA_DNA.fasta --write_bins 1 --score_threshold 0.2
5 --search_engine diamond -t 10 -o /datadrive05/Flo/Saliva/Saliva2/squeezemeta/squeezmeta_4thstrategy/K9_SALIVA_DNA/results/DAS/K9_SALIVA_DNA --db_directory /datadrive05/Flo/db/SqueezeMeta/db --debug
  Reading taxonomic assignments for contigs from /datadrive05/Flo/Saliva/Saliva2/squeezemeta/squeezmeta_4thstrategy/K9_SALIVA_DNA/intermediate/09.K9_SALIVA_DNA.contiglog
  Looking for DASTool bins in /datadrive05/Flo/Saliva/Saliva2/squeezemeta/squeezmeta_4thstrategy/K9_SALIVA_DNA/results/DAS/K9_SALIVA_DNA_DASTool_bins
  Output created in /datadrive05/Flo/Saliva/Saliva2/squeezemeta/squeezmeta_4thstrategy/K9_SALIVA_DNA/intermediate/17.K9_SALIVA_DNA.bintax
PATH=/home/constancias/miniconda3/envs/SqueezeMeta160321/SqueezeMeta/bin:/home/constancias/miniconda3/envs/SqueezeMeta160321/SqueezeMeta/bin/pplacer:/home/constancias/miniconda3/envs/SqueezeMeta160321/SqueezeMeta/bin/hmmer:$PATH /home/constancias/miniconda3/envs/SqueezeMeta160321/SqueezeMeta/bin/checkm taxon_set genus Streptococcus /da
tadrive05/Flo/Saliva/Saliva2/squeezemeta/squeezmeta_4thstrategy/K9_SALIVA_DNA/data/checkm_markers/Streptococcus.ms >> /datadrive05/Flo/Saliva/Saliva2/squeezemeta/squeezmeta_4thstrategy/K9_SALIVA_DNA/syslog 2>&1
Traceback (most recent call last):
  File "/home/constancias/miniconda3/envs/SqueezeMeta160321/SqueezeMeta/bin/checkm", line 45, in <module>
    from checkm import main
  File "/home/constancias/miniconda3/envs/SqueezeMeta160321/SqueezeMeta/bin/../lib/checkm/main.py", line 23, in <module>
    import numpy as np
ModuleNotFoundError: No module named 'numpy'
Linux scelse 5.4.0-66-generic #74~18.04.2-Ubuntu SMP Fri Feb 5 11:17:31 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

I installed Squeezemeta on  160321 using the conda reciepe and when trying to install numpy whithin the conda environment I got the following message: 

```
(SqueezeMeta160321) $ pip3 install numpy
Requirement already satisfied: numpy in /home/constancias/.local/lib/python3.6/site-packages (1.18.5)
```

I am using Squeezemeta in coassembly mode with the same dataset to explore different approaches and did not get any error.

Any idea what is happening here?

Thanks!

Flo

**Comment by fconstancias** [comment]
Please find attached the log file: [syslog.gz](https://github.com/jtamames/SqueezeMeta/files/6177836/syslog.gz)

**Comment by fpusan** [comment]
Hi!
pip3 is quite unreliable for installing packages. In this case, I think it is using the system's python interpreter (with local packages located at `/home/constancias/.local/lib/python3.6/site-packages`) instead of the conda python interpreter.

Try `python3 -m pip install numpy`. This will first open the interpreter present in `$PATH` (which should be conda's) and then use pip to install whatever package for that interpreter. Ideally, however, it would be better to use `conda install whatever`. I'm actually surprised that numpy was not installed by default (it gets installed when you install the `squeezemeta` package from conda.

**Comment by fconstancias** [comment]
Thanks for your answer. I am also quite surprised by the error since everything is OK (numpy as well) from the `test_install.pl` script

  ```

Checking the OS
        linux OK

Checking that tree is installed
        tree --help OK

Checking that ruby is installed
        ruby -h OK

Checking that java is installed
        java -h OK

Checking that all the required perl libraries are available in this environment
        perl -e 'use Term::ANSIColor' OK
        perl -e 'use DBI' OK
        perl -e 'use DBD::SQLite::Constants' OK
        perl -e 'use Time::Seconds' OK
        perl -e 'use Tie::IxHash' OK
        perl -e 'use Linux::MemInfo' OK
        perl -e 'use Getopt::Long' OK
        perl -e 'use File::Basename' OK
        perl -e 'use DBD::SQLite' OK
        perl -e 'use Data::Dumper' OK
        perl -e 'use Cwd' OK
        perl -e 'use XML::LibXML' OK
        perl -e 'use Term::ANSIColor' OK

Checking that all the required python libraries are available in this environment
        python3 -h OK
        python3 -c 'import numpy' OK
        python3 -c 'import scipy' OK
        python3 -c 'import matplotlib' OK
        python3 -c 'import dendropy' OK
        python3 -c 'import pysam' OK
        python3 -c 'import pandas' OK
        python3 -c 'import cython' OK
        python3 -c 'import future' OK

Checking that all the required R libraries are available in this environment
        R -h OK
        R -e 'library(doMC)' OK
        R -e 'library(ggplot2)' OK
        R -e 'library(data.table)' OK
        R -e 'library(reshape2)' OK
        R -e 'library(pathview)' OK
        R -e 'library(DASTool)' OK
        R -e 'library(SQMtools)' OK

Checking that SqueezeMeta is properly configured
        nr.db OK
        CheckM manifest OK
        LCA_tax DB OK

All checks successful

```


After sharing the error I actually used ` conda install -c anaconda numpy` and restarted the script and I still got the error...
