### ISSUE TITLE
sqm2tables.py giving ValueError: operands could not be broadcast together with shapes (0,) (11,) error

### ISSUE THREAD

**Issue by ShrutiKetan** [jtamames/SqueezeMeta#273]
Hi, 
 I have 11 samples running through the SqueezeMeta pipeline. It ran very smoothly and great results were generated. I wish to use SQMtools for further analysis. I am trying to use sqm2tables.py but after printing thousands of lines, it gives me:

Traceback (most recent call last):
  File "/gpfs1/scratch/shruti/anaconda3/envs/SqueezeMeta/SqueezeMeta/utils/sqm2tables.py", line 180, in <module>
    main(parse_args())
  File "/gpfs1/scratch/shruti/anaconda3/envs/SqueezeMeta/SqueezeMeta/utils/sqm2tables.py", line 63, in main
    sampleNames, orfs, kegg, cog, pfam, custom = parse_orf_table(perlVars['$mergedfile'], nokegg, nocog, nopfam, args.trusted_functions, args.ignore_unclassified, customMethods)
  File "/gpfs1/scratch/shruti/anaconda3/envs/SqueezeMeta/SqueezeMeta/utils/../lib/utils.py", line 167, in parse_orf_table
    orfs['tpm'] = tpm(orfs)
  File "/gpfs1/scratch/shruti/anaconda3/envs/SqueezeMeta/SqueezeMeta/utils/../lib/utils.py", line 104, in tpm
    fun_rpk = {fun: funDict['bases'][fun] / (fun_avgLengths[fun]/1000) for fun in funDict['bases']}
  File "/gpfs1/scratch/shruti/anaconda3/envs/SqueezeMeta/SqueezeMeta/utils/../lib/utils.py", line 104, in <dictcomp>
    fun_rpk = {fun: funDict['bases'][fun] / (fun_avgLengths[fun]/1000) for fun in funDict['bases']}
ValueError: operands could not be broadcast together with shapes (0,) (11,) 
Error in loadSQM("/gpfs1/scratch/shruti/NewRNASeq/SqueezemetaOut") : 
  An error occurred while running sqm2tables.py

sqm2kegg and most of the other scripts work fine! 
What should I do?
I am using Squeezemeta 1.1.1 through a Conda environment on my university cluster.

**Comment by fpusan** [comment]
Hi!
I kind of remember this bug having being solved at some point.
Can you retry with the latest SQM/SQMtools version?

**Comment by ShrutiKetan** [comment]
I will update them all to the latest version, rerun and get back to you! Thanks 🙂

Thanks & Regards,
Shruti Kutmutia (Ms)
Research Associate
60 Nanyang Drive, SBS-01N-27, Singapore 637551


[Image preview]               [cid:75265b94-63fc-4ccf-af93-2eea5e50b689]
________________________________
