### ISSUE TITLE
error at checkM_batch.pl line 161

### ISSUE THREAD

**Issue by slambrechts** [jtamames/SqueezeMeta#382]
Hi,

When SQM tries to run CheckM on the first of my 466 DASTool bins, it encounters an error at line 161 of `/home/slambrecht/miniconda2/envs/SqueezeMeta/SqueezeMeta/scripts/18.checkM_batch.pl` (full error message below). 

When looking at that line it says` if($ecode!=0) { die "Error running command:    $command"; }`

So it fails calling the CheckM command? Or is it more likely that there is something wrong with that specific bin?

```
Error running command:    PATH=/home/slambrecht/miniconda2/envs/SqueezeMeta/SqueezeMeta/bin:/home/slambrecht/miniconda2/envs/SqueezeMeta/SqueezeMeta/bin/pplacer:/home/slambrecht/miniconda2/envs/SqueezeMeta/SqueezeMeta/bin/hmmer:$PATH /home/slambrecht/miniconda2/envs/SqueezeMeta/SqueezeMeta/bin/checkm analyze -t 20 -x maxbin.0318.fasta.contigs.fa /home/slambrecht/MICROBIAN_metagenomics/SQM/microbian43/microbian43/data/checkm_markers/Actinobacteria.ms /home/slambrecht/MICROBIAN_metagenomics/SQM/microbian43/microbian43/results/DAS/microbian43_DASTool_bins /home/slambrecht/MICROBIAN_metagenomics/SQM/microbian43/microbian43/temp/checkm_batch >> /home/slambrecht/MICROBIAN_metagenomics/SQM/microbian43/microbian43/syslog 2>&1 at /home/slambrecht/miniconda2/envs/SqueezeMeta/SqueezeMeta/scripts/18.checkM_batch.pl line 161.
Stopping in STEP18 -> 18.checkM_batch.pl. Program finished abnormally

```

**Comment by fpusan** [comment]
Hi!
It might be both, though if it happens on the first one it looks like a problem with CheckM.
The output of checkm should be in `/home/slambrecht/MICROBIAN_metagenomics/SQM/microbian43/microbian43/syslog`. Maybe there we can get some clues.

**Comment by slambrechts** [comment]
Hi,

Thank you for pointing me to the `syslog` file! It seems to be some kind of permission denied error: `PermissionError: [Errno 13] Permission denied`. I worked with CheckM before, but I'm not entirely sure I used this specific CheckM that exists in my current SQM environment before. Should I check first whether the CheckM in this conda environment is working outside of the checkM_batch.pl script? Or do you think I missed a step during the installation of SQM? Full output from the syslog file:



```
[125 days, 15 hours, 0 minutes, 47 seconds]: STEP18 -> 18.checkM_batch.pl
PATH=/home/slambrecht/miniconda2/envs/SqueezeMeta/SqueezeMeta/bin:/home/slambrecht/miniconda2/envs/SqueezeMeta/SqueezeMeta/bin/pplacer:/home/slambrecht/miniconda2/envs/SqueezeMeta/SqueezeMeta/bin/hmmer:$PATH /home/slambrecht/miniconda2/envs/SqueezeMeta/SqueezeMeta/bin/checkm taxon_set phylum Actinobacteria /home/slambrecht/MICROBIAN_metagenomics/SQM/microbian43/microbian43/data/checkm_markers/Actinobacteria.ms >> /home/slambrecht/MICROBIAN_metagenomics/SQM/microbian43/microbian43/syslog 2>&1
Matplotlib is building the font cache; this may take a moment.

*******************************************************************************
 [CheckM - taxon_set] Generate taxonomic-specific marker set.
*******************************************************************************

  Marker set for Actinobacteria contains 204 marker genes arranged in 119 sets.
    Marker set inferred from 731 reference genomes.
  Marker set for Bacteria contains 104 marker genes arranged in 58 sets.
    Marker set inferred from 5449 reference genomes.

  Marker set written to: /home/slambrecht/MICROBIAN_metagenomics/SQM/microbian43/microbian43/data/checkm_markers/Actinobacteria.ms

  { Current stage: 0:00:02.874 || Total: 0:00:02.874 }
PATH=/home/slambrecht/miniconda2/envs/SqueezeMeta/SqueezeMeta/bin:/home/slambrecht/miniconda2/envs/SqueezeMeta/SqueezeMeta/bin/pplacer:/home/slambrecht/miniconda2/envs/SqueezeMeta/SqueezeMeta/bin/hmmer:$PATH /home/slambrecht/miniconda2/envs/SqueezeMeta/SqueezeMeta/bin/checkm analyze -t 20 -x maxbin.0318.fasta.contigs.fa /home/slambrecht/MICROBIAN_metagenomics/SQM/microbian43/microbian43/data/checkm_markers/Actinobacteria.ms /home/slambrecht/MICROBIAN_metagenomics/SQM/microbian43/microbian43/results/DAS/microbian43_DASTool_bins /home/slambrecht/MICROBIAN_metagenomics/SQM/microbian43/microbian43/temp/checkm_batch >> /home/slambrecht/MICROBIAN_metagenomics/SQM/microbian43/microbian43/syslog 2>&1

*******************************************************************************
 [CheckM - analyze] Identifying marker genes in bins.
*******************************************************************************

  Identifying marker genes in 1 bins with 20 threads:

Unexpected error: <class 'PermissionError'>
Traceback (most recent call last):
  File "/home/slambrecht/miniconda2/envs/SqueezeMeta/SqueezeMeta/bin/checkm", line 718, in <module>
    checkmParser.parseOptions(args)
  File "/home/slambrecht/miniconda2/envs/SqueezeMeta/SqueezeMeta/bin/../lib/checkm/main.py", line 1241, in parseOptions
    self.analyze(options)
  File "/home/slambrecht/miniconda2/envs/SqueezeMeta/SqueezeMeta/bin/../lib/checkm/main.py", line 302, in analyze
    options.bCalledGenes)
  File "/home/slambrecht/miniconda2/envs/SqueezeMeta/SqueezeMeta/bin/../lib/checkm/markerGeneFinder.py", line 58, in find
    workerQueue = mp.Queue()
  File "/home/slambrecht/miniconda2/envs/SqueezeMeta/lib/python3.6/multiprocessing/context.py", line 102, in Queue
    return Queue(maxsize, ctx=self.get_context())
  File "/home/slambrecht/miniconda2/envs/SqueezeMeta/lib/python3.6/multiprocessing/queues.py", line 42, in __init__
    self._rlock = ctx.Lock()
  File "/home/slambrecht/miniconda2/envs/SqueezeMeta/lib/python3.6/multiprocessing/context.py", line 67, in Lock
    return Lock(ctx=self.get_context())
  File "/home/slambrecht/miniconda2/envs/SqueezeMeta/lib/python3.6/multiprocessing/synchronize.py", line 162, in __init__
    SemLock.__init__(self, SEMAPHORE, 1, 1, ctx=ctx)
  File "/home/slambrecht/miniconda2/envs/SqueezeMeta/lib/python3.6/multiprocessing/synchronize.py", line 59, in __init__
    unlink_now)
PermissionError: [Errno 13] Permission denied
Stopping in STEP18 -> 18.checkM_batch.pl. Program finished abnormally

```

**Comment by fpusan** [comment]
```
  File "/home/slambrecht/miniconda2/envs/SqueezeMeta/lib/python3.6/multiprocessing/synchronize.py", line 59, in __init__
    unlink_now)
PermissionError: [Errno 13] Permission denied
```
This is a pretty arcane error in which python's multiprocessing module is failing. So I'd say it's not a problem with your data, checkm or SqueezeMeta... rather I'd say there is a problem with your environment.

Is this a cluster environment or your own workstation?
Do you have write permissions and enough free disk space in `/dev/shm/`?

**Comment by slambrechts** [comment]
This is on our own workstation. I installed SQM using the conda installation instructions listed at `https://github.com/jtamames/SqueezeMeta`. SQM version is `1.4.0, May 2021`

`/dev/shm$ df -k .` gives me:
```
Filesystem     1K-blocks  Used Available Use% Mounted on
udev           264112448     0 264112448   0% /dev
```

So I would guess there is enough free disk space in `/dev/shm/`. Not sure how to check if I have write permissions, but I would assume problems would have come up earlier if not, no?

**Comment by fpusan** [comment]
I see. Yes, that should have come up earlier. Maybe you were out of RAM at the moment?

`PATH=/home/slambrecht/miniconda2/envs/SqueezeMeta/SqueezeMeta/bin:/home/slambrecht/miniconda2/envs/SqueezeMeta/SqueezeMeta/bin/pplacer:/home/slambrecht/miniconda2/envs/SqueezeMeta/SqueezeMeta/bin/hmmer:$PATH /home/slambrecht/miniconda2/envs/SqueezeMeta/SqueezeMeta/bin/checkm analyze -t 20 -x maxbin.0318.fasta.contigs.fa /home/slambrecht/MICROBIAN_metagenomics/SQM/microbian43/microbian43/data/checkm_markers/Actinobacteria.ms /home/slambrecht/MICROBIAN_metagenomics/SQM/microbian43/microbian43/results/DAS/microbian43_DASTool_bins /home/slambrecht/MICROBIAN_metagenomics/SQM/microbian43/microbian43/temp/checkm_batch`

What happens if you run the command manually right now?

**Comment by slambrechts** [comment]
RAM should not be a problem I think, since our workstation has 504 GB RAM

When I run the command manually I get the same Permission denied error

**Comment by fpusan** [comment]
And with `ls -ltr /dev/` does `/dev/shm/` have rwx permissions for all users and groups?

**Comment by slambrechts** [comment]
I think so yes:

`drwxr-xr-x   2 root root            40 mei 28 09:48 shm`

full output:

```
slambrecht@WE11sv03:~$ ls -ltr /dev/
total 0
drwxr-xr-x   2 root root            60 mei 28 09:48 lightnvm
drwxr-xr-x   2 root root            60 mei 28 09:48 vfio
drwxr-xr-x   2 root root            60 mei 28 09:48 net
drwxr-xr-x   3 root root            60 mei 28 09:48 bus
drwxr-xr-x   2 root root             0 mei 28 09:48 pts
lrwxrwxrwx   1 root root            15 mei 28 09:48 stdout -> /proc/self/fd/1
lrwxrwxrwx   1 root root            15 mei 28 09:48 stdin -> /proc/self/fd/0
lrwxrwxrwx   1 root root            15 mei 28 09:48 stderr -> /proc/self/fd/2
lrwxrwxrwx   1 root root            13 mei 28 09:48 fd -> /proc/self/fd
lrwxrwxrwx   1 root root            11 mei 28 09:48 core -> /proc/kcore
drwxr-xr-x   2 root root           100 mei 28 09:48 bsg
drwxr-xr-x   8 root root           160 mei 28 09:48 disk
drwxr-xr-x   2 root root           340 mei 28 09:48 block
drwxr-xr-x   2 root root           120 mei 28 09:48 mapper
drwxr-xr-x   2 root root            40 mei 28 09:48 shm
drwxr-xr-x   2 root root            40 mei 28 09:48 mqueue
lrwxrwxrwx   1 root root            28 mei 28 09:48 log -> /run/systemd/journal/dev-log
lrwxrwxrwx   1 root root            12 mei 28 09:48 initctl -> /run/initctl
drwxr-xr-x   2 root root            40 mei 28 09:48 hugepages
crw-------   1 root root       10, 249 mei 28 09:48 zfs
crw-------   1 root root       10, 241 mei 28 09:48 vhost-vsock
crw-------   1 root root       10, 238 mei 28 09:48 vhost-net
crw-------   1 root root       10, 137 mei 28 09:48 vhci
crw-------   1 root root       10, 240 mei 28 09:48 userio
crw-------   1 root root       10, 239 mei 28 09:48 uhid
drwxr-xr-x   2 root root            80 mei 28 09:48 snd
crw-------   1 root root       10, 144 mei 28 09:48 nvram
crw-------   1 root root       10, 203 mei 28 09:48 cuse
crw-------   1 root root       89,   0 mei 28 09:48 i2c-0
crw-------   1 root root       89,   1 mei 28 09:48 i2c-1
crw-rw----   1 root disk       21,   2 mei 28 09:48 sg2
crw-rw----   1 root disk       21,   1 mei 28 09:48 sg1
crw-rw----   1 root dialout     4,  77 mei 28 09:48 ttyS13
crw-rw----   1 root dialout     4,  76 mei 28 09:48 ttyS12
crw-rw----   1 root dialout     4,  74 mei 28 09:48 ttyS10
crw-rw----   1 root dialout     4,  86 mei 28 09:48 ttyS22
crw-rw----   1 root dialout     4,  83 mei 28 09:48 ttyS19
crw-rw----   1 root dialout     4,  81 mei 28 09:48 ttyS17
crw-rw----   1 root dialout     4,  80 mei 28 09:48 ttyS16
crw-rw----   1 root dialout     4,  79 mei 28 09:48 ttyS15
crw-rw----   1 root dialout     4,  78 mei 28 09:48 ttyS14
crw-rw----   1 root dialout     4,  75 mei 28 09:48 ttyS11
crw-rw----   1 root dialout     4,  94 mei 28 09:48 ttyS30
crw-rw----   1 root dialout     4,  93 mei 28 09:48 ttyS29
crw-rw----   1 root dialout     4,  92 mei 28 09:48 ttyS28
crw-rw----   1 root dialout     4,  90 mei 28 09:48 ttyS26
crw-rw----   1 root dialout     4,  89 mei 28 09:48 ttyS25
crw-rw----   1 root dialout     4,  88 mei 28 09:48 ttyS24
crw-rw----   1 root dialout     4,  87 mei 28 09:48 ttyS23
crw-rw----   1 root dialout     4,  85 mei 28 09:48 ttyS21
crw-rw----   1 root dialout     4,  84 mei 28 09:48 ttyS20
crw-rw----   1 root dialout     4,  66 mei 28 09:48 ttyS2
crw-rw----   1 root dialout     4,  82 mei 28 09:48 ttyS18
crw-rw----   1 root dialout     4,  65 mei 28 09:48 ttyS1
crw-------   1 root root      249,   0 mei 28 09:48 rtc0
lrwxrwxrwx   1 root root             4 mei 28 09:48 rtc -> rtc0
crw-rw----   1 root dialout     4,  73 mei 28 09:48 ttyS9
crw-rw----   1 root dialout     4,  72 mei 28 09:48 ttyS8
crw-rw----   1 root dialout     4,  71 mei 28 09:48 ttyS7
crw-rw----   1 root dialout     4,  70 mei 28 09:48 ttyS6
crw-rw----   1 root dialout     4,  69 mei 28 09:48 ttyS5
crw-rw----   1 root dialout     4,  68 mei 28 09:48 ttyS4
crw-rw----   1 root dialout     4,  95 mei 28 09:48 ttyS31
crw-rw----   1 root dialout     4,  67 mei 28 09:48 ttyS3
crw-rw----   1 root dialout     4,  91 mei 28 09:48 ttyS27
crw-rw----   1 root dialout     4,  64 mei 28 09:48 ttyS0
crw-rw----   1 root disk       21,   0 mei 28 09:48 sg0
drwxr-x---   3 root vboxusers       60 mei 28 09:48 vboxusb
crw-r--r--   1 root root        1,  11 mei 28 09:48 kmsg
crw-rw-rw-   1 root root        1,   7 mei 28 09:48 full
crw-rw-rw-   1 root root        1,   5 mei 28 09:48 zero
crw-rw-rw-   1 root root        1,   9 mei 28 09:48 urandom
crw-rw-r--   1 root netdev     10, 242 mei 28 09:48 rfkill
crw-rw-rw-   1 root root        1,   8 mei 28 09:48 random
crw-r-----   1 root kmem        1,   4 mei 28 09:48 port
crw-rw-rw-   1 root root        1,   3 mei 28 09:48 null
crw-r-----   1 root kmem        1,   1 mei 28 09:48 mem
crw-------   1 root root       10, 227 mei 28 09:48 mcelog
crw-------   1 root root       10, 183 mei 28 09:48 hwrng
crw-------   1 root root       10, 228 mei 28 09:48 hpet
crw-------   1 root root       10,  62 mei 28 09:48 ecryptfs
crw-------   1 root root       10,  59 mei 28 09:48 cpu_dma_latency
crw-r--r--   1 root root       10, 235 mei 28 09:48 autofs
crw-------   1 root root       10,  63 mei 28 09:48 vga_arbiter
crw-------   1 root root       10, 223 mei 28 09:48 uinput
crw-rw----   1 root kvm        10,  60 mei 28 09:48 udmabuf
crw-------   1 root root       10, 231 mei 28 09:48 snapshot
crw-------   1 root root      108,   0 mei 28 09:48 ppp
crw-------   1 root root       10,   1 mei 28 09:48 psaux
crw--w----   1 root tty         4,  10 mei 28 09:48 tty10
crw--w----   1 root tty         4,   0 mei 28 09:48 tty0
crw--w----   1 root tty         4,  35 mei 28 09:48 tty35
crw--w----   1 root tty         4,  34 mei 28 09:48 tty34
crw--w----   1 root tty         4,   3 mei 28 09:48 tty3
crw--w----   1 root tty         4,  28 mei 28 09:48 tty28
crw--w----   1 root tty         4,  27 mei 28 09:48 tty27
crw--w----   1 root tty         4,  26 mei 28 09:48 tty26
crw--w----   1 root tty         4,  25 mei 28 09:48 tty25
crw--w----   1 root tty         4,  24 mei 28 09:48 tty24
crw--w----   1 root tty         4,  23 mei 28 09:48 tty23
crw--w----   1 root tty         4,  22 mei 28 09:48 tty22
crw--w----   1 root tty         4,  21 mei 28 09:48 tty21
crw--w----   1 root tty         4,  20 mei 28 09:48 tty20
crw--w----   1 root tty         4,   2 mei 28 09:48 tty2
crw--w----   1 root tty         4,  19 mei 28 09:48 tty19
crw--w----   1 root tty         4,  18 mei 28 09:48 tty18
crw--w----   1 root tty         4,  17 mei 28 09:48 tty17
crw--w----   1 root tty         4,  16 mei 28 09:48 tty16
crw--w----   1 root tty         4,  15 mei 28 09:48 tty15
crw--w----   1 root tty         4,  14 mei 28 09:48 tty14
crw--w----   1 root tty         4,  13 mei 28 09:48 tty13
crw--w----   1 root tty         4,  12 mei 28 09:48 tty12
crw--w----   1 root tty         4,  11 mei 28 09:48 tty11
crw--w----   1 root tty         4,  56 mei 28 09:48 tty56
crw--w----   1 root tty         4,  51 mei 28 09:48 tty51
crw--w----   1 root tty         4,   5 mei 28 09:48 tty5
crw--w----   1 root tty         4,  45 mei 28 09:48 tty45
crw--w----   1 root tty         4,  44 mei 28 09:48 tty44
crw--w----   1 root tty         4,  42 mei 28 09:48 tty42
crw--w----   1 root tty         4,   4 mei 28 09:48 tty4
crw--w----   1 root tty         4,  39 mei 28 09:48 tty39
crw--w----   1 root tty         4,  37 mei 28 09:48 tty37
crw--w----   1 root tty         4,  36 mei 28 09:48 tty36
crw--w----   1 root tty         4,  33 mei 28 09:48 tty33
crw--w----   1 root tty         4,  30 mei 28 09:48 tty30
crw--w----   1 root tty         4,  29 mei 28 09:48 tty29
crw-------   1 root root      240,   0 mei 28 09:48 hidraw0
crw-rw----   1 root tty         7,   1 mei 28 09:48 vcs1
crw-------   1 root root        5,   3 mei 28 09:48 ttyprintk
crw--w----   1 root tty         4,   9 mei 28 09:48 tty9
crw--w----   1 root tty         4,   8 mei 28 09:48 tty8
crw--w----   1 root tty         4,   7 mei 28 09:48 tty7
crw--w----   1 root tty         4,  63 mei 28 09:48 tty63
crw--w----   1 root tty         4,  62 mei 28 09:48 tty62
crw--w----   1 root tty         4,  61 mei 28 09:48 tty61
crw--w----   1 root tty         4,  60 mei 28 09:48 tty60
crw--w----   1 root tty         4,   6 mei 28 09:48 tty6
crw--w----   1 root tty         4,  59 mei 28 09:48 tty59
crw--w----   1 root tty         4,  57 mei 28 09:48 tty57
crw--w----   1 root tty         4,  55 mei 28 09:48 tty55
crw--w----   1 root tty         4,  54 mei 28 09:48 tty54
crw--w----   1 root tty         4,  52 mei 28 09:48 tty52
crw--w----   1 root tty         4,  46 mei 28 09:48 tty46
crw--w----   1 root tty         4,  43 mei 28 09:48 tty43
crw--w----   1 root tty         4,  41 mei 28 09:48 tty41
crw--w----   1 root tty         4,  40 mei 28 09:48 tty40
crw--w----   1 root tty         4,  38 mei 28 09:48 tty38
crw--w----   1 root tty         4,  32 mei 28 09:48 tty32
crw--w----   1 root tty         4,  31 mei 28 09:48 tty31
crw-------   1 root root      240,   1 mei 28 09:48 hidraw1
crw-rw----   1 root tty         7,  69 mei 28 09:48 vcsu5
crw-rw----   1 root tty         7,  67 mei 28 09:48 vcsu3
crw-rw----   1 root tty         7,  66 mei 28 09:48 vcsu2
crw-rw----   1 root tty         7,  65 mei 28 09:48 vcsu1
crw-rw----   1 root tty         7, 131 mei 28 09:48 vcsa3
crw-rw----   1 root tty         7, 130 mei 28 09:48 vcsa2
crw-rw----   1 root tty         7, 129 mei 28 09:48 vcsa1
crw-rw----   1 root tty         7, 128 mei 28 09:48 vcsa
crw-rw----   1 root tty         7,   6 mei 28 09:48 vcs6
crw-rw----   1 root tty         7,   4 mei 28 09:48 vcs4
crw-rw----   1 root tty         7,   3 mei 28 09:48 vcs3
crw-rw----   1 root tty         7,   2 mei 28 09:48 vcs2
crw-rw----   1 root tty         7,   0 mei 28 09:48 vcs
crw--w----   1 root tty         4,  58 mei 28 09:48 tty58
crw--w----   1 root tty         4,  53 mei 28 09:48 tty53
crw--w----   1 root tty         4,  50 mei 28 09:48 tty50
crw--w----   1 root tty         4,  49 mei 28 09:48 tty49
crw--w----   1 root tty         4,  48 mei 28 09:48 tty48
crw--w----   1 root tty         4,  47 mei 28 09:48 tty47
crw-rw----   1 root tty         7,  70 mei 28 09:48 vcsu6
crw-rw----   1 root tty         7, 132 mei 28 09:48 vcsa4
crw-rw----   1 root tty         7,  68 mei 28 09:48 vcsu4
crw-rw----   1 root tty         7,  64 mei 28 09:48 vcsu
crw-rw----   1 root tty         7, 134 mei 28 09:48 vcsa6
crw-rw----   1 root tty         7,   5 mei 28 09:48 vcs5
crw-rw----   1 root tty         7, 133 mei 28 09:48 vcsa5
drwxr-xr-x   4 root root           180 mei 28 09:48 input
crw-------   1 root root       89,   2 mei 28 09:48 i2c-2
crw-rw----   1 root video      29,   0 mei 28 09:48 fb0
drwxr-xr-x   3 root root            80 mei 28 09:48 dri
crw-------   1 root root      238,   0 mei 28 09:48 ipmi0
crw-------   1 root root      246,   0 mei 28 09:48 ptp0
crw-------   1 root root      247,   0 mei 28 09:48 pps0
crw-------   1 root root      246,   1 mei 28 09:48 ptp1
crw-------   1 root root      247,   1 mei 28 09:48 pps1
crw--w----   1 root tty         4,   1 mei 28 09:48 tty1
crw--w----   1 root tty         5,   1 mei 28 09:48 console
drwxr-xr-x  42 root root           860 jun  4 06:49 cpu
crw-rw----   1 root disk       10, 234 jun  4 06:50 btrfs-control
crw-rw----   1 root disk       10, 237 sep 20 19:32 loop-control
crw-rw----+  1 root kvm        10, 232 sep 20 19:32 kvm
crw-rw-rw-   1 root root       10, 229 sep 20 19:32 fuse
brw-rw----   1 root disk        7,   7 sep 20 19:33 loop7
brw-rw----   1 root disk        7,   6 sep 20 19:33 loop6
brw-rw----   1 root disk        8,  16 sep 20 19:33 sdb
brw-rw----   1 root disk        8,  32 sep 20 19:33 sdc
brw-rw----   1 root disk      253,   0 sep 20 19:33 dm-0
brw-rw----   1 root disk      253,   1 sep 20 19:33 dm-1
brw-rw----   1 root disk      253,   2 sep 20 19:33 dm-2
brw-rw----   1 root disk        8,   0 sep 20 19:33 sda
brw-rw----   1 root disk        8,   1 sep 20 19:33 sda1
brw-rw----   1 root disk        7,   2 okt 11 22:19 loop2
crw-rw-rw-   1 root root       10,  57 okt 13 08:46 vboxdrvu
crw-------   1 root root       10,  58 okt 13 08:46 vboxdrv
crw-------   1 root root       10,  56 okt 13 08:46 vboxnetctl
drwxr-xr-x   2 root root          4540 okt 13 08:46 char
brw-rw----   1 root disk        7,   4 okt 19 18:54 loop4
brw-rw----   1 root disk        7,   5 okt 19 18:54 loop5
brw-rw----   1 root disk        7,   0 okt 20 00:49 loop0
brw-rw----   1 root disk        7,   1 nov  4 19:45 loop1
brw-rw----   1 root disk        7,   3 nov  4 19:45 loop3
crw-rw-rw-   1 root tty         5,   0 nov  8 16:25 tty
crw-rw-rw-   1 root tty         5,   2 nov  9 12:00 ptmx

```

**Comment by fpusan** [comment]
I don't think other users or groups other than root have write permissions there.
In my workstation it looks like this instead.
`drwxrwxrwt   3 root root          80 nov  9 12:07 shm`
What about running the same checkm call as before, but now as root? (assuming you have root access there)

**Comment by slambrechts** [comment]
Ah ok, so that would be the cause of the problem then. I don't have root access. Can I redirect to use a different directory then `/dev/shm/`, or is this fixed in/specific to CheckM?

**Comment by fpusan** [comment]
This is not even an issue of CheckM anymore.
`shm` is a virtual disk that actually points directly to your RAM memory rather than a SSD/HDD. It is used for sharing memory between different processes. In this case, the multiprocessing module from python (which CheckM imports) is attempting to use shm, but I suspect it fails due to lack of permissions.
So unless you go into python's own source code I don't think you can change it (also even if you somehow managed to do it, I think there would be a large speed penalty). Can you ask the administrator of your workstation to check whether this is truly a permissions issue?

**Comment by slambrechts** [comment]
Ok thanks for the info, I will contact the administrator. If it's not a permissions issue, can it be that I'm starting to take up too much space? My SQM folder is getting rather large (> 2.3 TB). And if so, can I for example delete the sam files? Or are they still used in steps 18-22 of the pipeline?

**Comment by fpusan** [comment]
You could delete them if you want to (unless you want to run anvi'o later) but disk usage should be unrelated to this issue.

**Comment by slambrechts** [comment]
ok thanks
