### ISSUE TITLE
STEP18: It seems that the CheckM data folder has not been set yet or has been removed.

### ISSUE THREAD

**Issue by fpusan** [jtamames/SqueezeMeta#398]
[10 hours, 32 minutes, 4 seconds]: STEP18 -> 18.checkM_batch.pl
PATH=/opt/conda/envs/SqueezeMeta-2020.11/SqueezeMeta/bin:/opt/conda/envs/SqueezeMeta-2020.11/SqueezeMeta/bin/pplacer:/opt/conda/envs/SqueezeMeta-2020.11/SqueezeMeta/bin/hmmer:$PATH /opt/conda/envs/SqueezeMeta-2020.11/SqueezeMeta/bin/checkm taxon_set phylum Elusimicrobia /work/las-research/students/las_djorton/Hadza/data/checkm_markers/Elusimicrobia.ms >> /work/las-research/students/las_djorton/Hadza/syslog 2>&1

*******************************************************************************
 [CheckM - taxon_set] Generate taxonomic-specific marker set.
*******************************************************************************

It seems that the CheckM data folder has not been set yet or has been removed. Running: 'checkm data setRoot'.
You do not seem to have permission to edit the checkm config file
located at /opt/conda/envs/SqueezeMeta-2020.11/SqueezeMeta/lib/checkm/DATA_CONFIG
Please try again with updated privileges. Error was:

[Errno 30] Read-only file system: '/opt/conda/envs/SqueezeMeta-2020.11/SqueezeMeta/lib/checkm/DATA_CONFIG'
Sorry, CheckM cannot run without a valid data folder.

Unexpected error: <class 'FileNotFoundError'>
Traceback (most recent call last):
  File "/opt/conda/envs/SqueezeMeta-2020.11/SqueezeMeta/bin/checkm", line 718, in <module>
    checkmParser.parseOptions(args)
  File "/opt/conda/envs/SqueezeMeta-2020.11/SqueezeMeta/bin/../lib/checkm/main.py", line 1239, in parseOptions
    self.taxonSet(options)
  File "/opt/conda/envs/SqueezeMeta-2020.11/SqueezeMeta/bin/../lib/checkm/main.py", line 262, in taxonSet
    bValidSet = taxonParser.markerSet(options.rank, options.taxon, options.marker_file)
  File "/opt/conda/envs/SqueezeMeta-2020.11/SqueezeMeta/bin/../lib/checkm/taxonParser.py", line 82, in markerSet
    taxonMarkerSets = self.readMarkerSets()
  File "/opt/conda/envs/SqueezeMeta-2020.11/SqueezeMeta/bin/../lib/checkm/taxonParser.py", line 40, in readMarkerSets
    for line in open(DefaultValues.TAXON_MARKER_SETS):
FileNotFoundError: [Errno 2] No such file or directory: 'taxon_marker_sets.tsv'
Stopping in STEP18 -> 18.checkM_batch.pl. Program finished abnormally

The latest in this series of issues. Thank you for your continued support with this.

_Originally posted by @dorton21 in https://github.com/jtamames/SqueezeMeta/issues/355#issuecomment-985074856_

**Comment by fpusan** [comment]
@dorton21 I moved this to a new issue.
Does `test_install.pl` complain about checkm installation?
The problem likely comes from an improperly configured installation of SqueezeMeta.
The file `/opt/conda/envs/SqueezeMeta-2020.11/SqueezeMeta/lib/checkm/DATA_CONFIG` should contain the proper paths to the databases. You can check manually whether this is the case.
It seems that you don't have permission to edit it, so `configure_nodb.pl` (which would be the easy solution here) will fail.
Let me know what happens with `test_install.pl` and whether `DATA_CONFIG` has the right path to the database. If it doesn't, an administrator should run `configure_nodb.pl` for you, and `test_install.pl` should finish without errors.

**Comment by fpusan** [comment]
Closing due to lack of activity, feel free to reopen
