### ISSUE TITLE
What folders do I need in order to run loadSQM?

### ISSUE THREAD

**Issue by mradz19** [jtamames/SqueezeMeta#402]
I cannot install SQMtools on my server so I will need to download the project directory and do it locally. If I have to download the entire project it will take a very long time, so what folders within the project can I remove to make the download quicker and still be able to load an SQM project?

**Comment by mradz19** [comment]
I did transfer everything except the data folder as I think that is where most of stoage heavy files are. I tried to loadSQM on my local computer but I am getting this error:
```
loadSQM("bone_project_spades/")
Generating tabular outputs for project in bone_project_spades/
sh: /kusers/ancillary/mradzieta/anaconda3/envs/SqueezeMeta/SqueezeMeta/utils/sqm2tables.py: No such file or directory
Error in loadSQM("bone_project_spades/") : 
  An error occurred while running sqm2tables.py
In addition: Warning message:
In system(command) : error in running command
```

For some reason it appears to be attempting to run sqm2tables.py from the conda environment on the server that I did the run rather than locally where I have SQMtools installed.

**Comment by fpusan** [comment]
I would recommend to manually run `sqm2tables.py` in your server before copying the project to your local computer.
`sqm2tables.py /path/to/your/project /path/to/your/project/results/tables`

**Comment by mradz19** [comment]
I did manage to install SQMtools on the server, however when I run loadSQM I get the following error:
```
spades=loadSQM("bone_project_spades/")
Generating tabular outputs for project in bone_project_spades/
Traceback (most recent call last):
  File "/kusers/ancillary/mradzieta/anaconda3/envs/SqueezeMeta/SqueezeMeta/utils/sqm2tables.py", line 218, in <module>
    main(parse_args())
  File "/kusers/ancillary/mradzieta/anaconda3/envs/SqueezeMeta/SqueezeMeta/utils/sqm2tables.py", line 190, in main
    tax_abunds_contigs[unmapped_str] = total_reads - sum(tax_abunds_contigs.values())
ValueError: operands could not be broadcast together with shapes (59,) (60,) 
Error in loadSQM("bone_project_spades/") : 
  An error occurred while running sqm2tables.py
```

**Comment by mradz19** [comment]
I also tried using the sqm2tables.py script and for the same error:
```
qm2tables.py bone_project_spades/ test/
Traceback (most recent call last):
  File "/kusers/ancillary/mradzieta/anaconda3/envs/SqueezeMeta/bin/sqm2tables.py", line 218, in <module>
    main(parse_args())
  File "/kusers/ancillary/mradzieta/anaconda3/envs/SqueezeMeta/bin/sqm2tables.py", line 190, in main
    tax_abunds_contigs[unmapped_str] = total_reads - sum(tax_abunds_contigs.values())
ValueError: operands could not be broadcast together with shapes (59,) (60,) 
```

**Comment by mradz19** [comment]
Also I am using the latest versions of SQMtools and SqueezeMeta

**Comment by fpusan** [comment]
You don't need to install SQMtools in order to manually run `sqm2tables.py`.
How many samples are there in your project? It seems that somehow the contigs file and the mappingstats file include a different number of samples.
Can you share those with me? They would be 10.*.mappingstat and 19.*.contigtable. For the contigtable I only need the first 10 lines.

**Comment by mradz19** [comment]
That is the mapping stat (poor mapping for some samples I am looking at different approaches):
```
3_DNA   1778416 721876  40.59   202868085
4_DNA   1626646 612270  37.64   189526241
5_DNA   132315334	130994708	99.00   18016390637
7_DNA   1025418 671410  65.48   127126394
8_DNA   922592  374672  40.61   107160045
9_DNA   174400  88900   50.97   25628323
11_DNA  448252  302762  67.54   65923602
12_DNA  231376  122250  52.84   34176334
13_DNA  732516  285278  38.94   87332279
14_DNA  1513854 634034  41.88   193282935
15_DNA  1440820 624604  43.35   179174841
16_DNA  5886720 4953692 84.15   765676217
17_DNA  1701420 710628  41.77   193664982
18_DNA  563600  414028  73.46   75809154
19_DNA  1610924 652054  40.48   182326612
20_DNA  1365446 571596  41.86   155487021
21_DNA  382518  176646  46.18   46524986
23_DNA  1592552 893342  56.09   189551402
24_DNA  1330684 562522  42.27   154420126
25_DNA  21999514        21608738        98.22   2987051666
26_DNA  2046160 1023414 50.02   236174286
27_DNA  1504830 640216  42.54   176630348
28_DNA  7605038 5879358 77.31   947334223
29_DNA  4144516 1490980 35.97   477276336
30_DNA  1855700 877282  47.27   230220180
31_DNA  4884984 1653998 33.86   579436342
32_DNA  2621838 1125654 42.93   293535800
33_DNA  4480748 3445238 76.89   580934488
34_DNA  2268954 990300  43.65   256309468
35_DNA  3886620 1327576 34.16   464527639
36_DNA  13238450        11015190        83.21   1537052998
37_DNA  81547368        79808078        97.87   10800613371
Z_DNA   23024242        22864860        99.31   3178923857
43_RNA  13833526        1236966 8.94    1293819530
40_RNA  10541960        1080326 10.25   997392987
14_RNA  8964956 2324390 25.93   890979993
41_RNA  11636572        2101464 18.06   1137312470
17_RNA  17450682        2004504 11.49   1644281404
19_RNA  21024056        2875510 13.68   1807253620
20_RNA  11342858        979032  8.63    1081501456
21_RNA  13051768        6211094 47.59   1279680506
42_RNA  95868942        81216242        84.72   9785538888
23_RNA  33134790        21738212        65.61   3307894013
24_RNA  10198834        1781414 17.47   977059253
25_RNA  212917180	207033518	97.24   21505060030
7_RNA   7654134 848298  11.08   731315544
34_RNA  8904340 3602470 40.46   855244596
39_RNA  201359732	160106654	79.51   19819670864
8_RNA   9954194 2068250 20.78   811475038
32_RNA  17530552        3226710 18.41   1315237257
12_RNA  14696908        2057854 14.00   1068298518
4_RNA   6513912 699996  10.75   561897875
11_RNA  32619896        12880684        39.49   2828777849
27_RNA  12862800        2486810 19.33   1177245712
9_RNA   4858684 1033262 21.27   453953427
26_RNA  38880209        30799077        79.22   3870669593
3_RNA   4129294 450010  10.90   372653404
44_RNA  30963486        23042782        74.42   2977585639
36_RNA  53729351        48796445        90.82   5359116453
```

And this is 20.*.contigtable:
```
#Created by /kusers/ancillary/mradzieta/anaconda3/envs/SqueezeMeta/SqueezeMeta/scripts/20.getcontigs.pl, Tue Dec  7 21:05:15 2021
Contig ID	Tax     Disparity	GC perc Length  Num genes	Bin ID  Coverage 3_DNA  TPM 3_DNA	Raw read count 3_DNA    Coverage 4_DNA  TPM 4_DNA	Raw read count 4_DNA    Coverage 5_DNA  TPM 5_DNA	Raw read count 5_DNA    Coverage 7_DNA  TPM 7_D>
sp                      0.00                            0.000   0.000   0	0.000   0.000   0	0.000   0.000   0	0.000   0.000   0	0.000   0.000   0	0.000   0.000   0	0.000   0.000   0	0.000   0.000   0	0.000   0.000   0      >
spades_1        k_Bacteria;p_Proteobacteria;c_Gammaproteobacteria;o_Enterobacterales;f_Enterobacteriaceae;g_Citrobacter 0.055   51.61   1303652 1223    maxbin.023	0.000   0.000   2	0.000   0.000   2	319.020 291.000 3090081 0.000   0.000   22	0.000  >
spades_2        k_Bacteria;p_Proteobacteria;c_Gammaproteobacteria;o_Enterobacterales;f_Enterobacteriaceae;g_Citrobacter 0.029   51.95   1293559 1212    maxbin.023	0.000   0.000   0	0.000   0.000   2	316.470 288.700 3041981 0.000   0.000   16	0.000  >
spades_3        k_Bacteria;n_Terrabacteria group;p_Actinobacteria;c_Coriobacteriia;o_Coriobacteriales;f_Atopobiaceae;g_Atopobium        0.010   49.19   989105  873     maxbin.044	0.000   0.000   0	0.000   0.000   0	0.000   0.000   0	0.000   0.000  >
spades_4        k_Bacteria;p_Proteobacteria;c_Gammaproteobacteria;o_Enterobacterales;f_Yersiniaceae;g_Serratia  0.016   60.24   895159  830     maxbin.027	0.000   0.000   0	0.000   0.000   0	30.810  28.200  205687  0.000   0.000   2	0.000   0.000  >
spades_5        k_Bacteria;n_Terrabacteria group;p_Firmicutes;c_Bacilli;o_Lactobacillales;f_Streptococcaceae;g_Streptococcus;s_Streptococcus agalactiae 0.000   35.21   872080  824     maxbin.024	0.000   0.000   0	0.000   0.000   0	0.000   0.000   34     >
spades_6        k_Bacteria;p_Proteobacteria;c_Gammaproteobacteria;o_Pseudomonadales;f_Pseudomonadaceae;g_Pseudomonas;species n_Pseudomonas aeruginosa group;s_Pseudomonas aeruginosa    0.006   66.27   847967  810     maxbin.030	0.000   0.000   0	0.000   0.000  >
spades_7        k_Bacteria;n_Terrabacteria group;p_Firmicutes;c_Negativicutes;o_Veillonellales;f_Veillonellaceae;g_Veillonella  0.024   37.64   841131  778     maxbin.025	0.000   0.000   0	0.000   0.000   2	0.000   0.000   3	0.480   5.200   3052   >
spades_8        k_Bacteria;p_Proteobacteria;c_Gammaproteobacteria;o_Enterobacterales;f_Morganellaceae;g_Morganella;s_Morganella morganii        0.023   49.90   834739  821     maxbin.026	0.000   0.000   0	0.000   0.000   0	0.000   0.000   9	0.000  >
```

**Comment by fpusan** [comment]
I can not see the whole range of columns in the contig table from that paste. Can you share the first lines with me as a file?

**Comment by mradz19** [comment]
[Untitled 2.txt](https://github.com/jtamames/SqueezeMeta/files/7684591/Untitled.2.txt)
Ok that is the first few lines with sample IDs

**Comment by fpusan** [comment]
Yeah, so there seems to be an extra sample named "sp" at the end of you contigs table, that is not present in the mappingstat.
Any idea on what it could be?

**Comment by mradz19** [comment]
No idea what that could be.. I don't have anything in the sample file by that name

**Comment by fpusan** [comment]
This is very weird. Can you share the whole file with us?

If this was a normal bug on our part then it would be happening in every run of SqueezeMeta, which clearly isn't the case.

Did you do something to the project? Restarted it changing something? Maybe changed some code when trying to fix another issue? Or edited the contigtable file? I know that probably you didn't, but just trying to discard some options.

**Comment by jtamames** [comment]
And the samples file too, please
