### ISSUE TITLE
Running Concoct

### ISSUE THREAD

**Issue by Sewunet-Abera** [jtamames/SqueezeMeta#494]
Hello,
Thank you so much for developing such a nice tool.
Since maxbin is running slow, I wanted to run concoct in parallel following the issue #69.
But instead of maxbin, I renamed the file to metabat2 and the bin directory to metabat2.
It runs for a while and I end up getting the following error. Thanks in advance for your help;

sewuneta@nioo0003:~/sorghum_shotgun_metagenome_analysis/SqueezeMeta$ restart.pl sqmeta11 -step 15
restart.pl: command not found
sewuneta@nioo0003:~/sorghum_shotgun_metagenome_analysis/SqueezeMeta$ conda activate SqueezeMeta
              
(SqueezeMeta) sewuneta@nioo0003:~/sorghum_shotgun_metagenome_analysis/SqueezeMeta$ restart.pl sqmeta11 -step 15
[0 seconds]: STEP15 -> METABAT BINNING: 15.bin_metabat2.pl
samtools: error while loading shared libraries: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/home/NIOO.INT/sewuneta/.conda/envs/SqueezeMeta/bin/scripts/concoct_coverage_table.py", line 91, in <module>
    generate_input_table(args.bedfile, args.bamfiles, samplenames=samplenames)
  File "/home/NIOO.INT/sewuneta/.conda/envs/SqueezeMeta/bin/scripts/concoct_coverage_table.py", line 41, in generate_input_table
    sys.stderr.write(out)
TypeError: write() argument must be str, not bytes
Traceback (most recent call last):
  File "/home/NIOO.INT/sewuneta/.conda/envs/SqueezeMeta/bin/scripts/merge_cutup_clustering.py", line 66, in <module>
    main(args)
  File "/home/NIOO.INT/sewuneta/.conda/envs/SqueezeMeta/bin/scripts/merge_cutup_clustering.py", line 31, in main
    with open(args.cutup_clustering_result, 'r') as ifh:
FileNotFoundError: [Errno 2] No such file or directory: '/home/nioo/sewuneta/sorghum_shotgun_metagenome_analysis/SqueezeMeta/sqmeta11/results/concoct/concoct_int/clustering_gt1000.csv'
wc: /home/nioo/sewuneta/sorghum_shotgun_metagenome_analysis/SqueezeMeta/sqmeta11/results/concoct/: Is a directory
WARNING in STEP15 -> 15.bin_metabat2.pl. File /home/nioo/sewuneta/sorghum_shotgun_metagenome_analysis/SqueezeMeta/sqmeta11/results/concoct/ is empty, no Metabat2 results!
[32 minutes, 7 seconds]: STEP16 -> DAS_TOOL MERGING: 16.dastool.pl
mkdir: cannot create directory ‘/home/nioo/sewuneta/sorghum_shotgun_metagenome_analysis/SqueezeMeta/sqmeta11/results/DAS’: File exists
Error running command:    LD_LIBRARY_PATH=/home/nioo/sewuneta/.conda/envs/SqueezeMeta/SqueezeMeta/lib PATH=/home/nioo/sewuneta/.conda/envs/SqueezeMeta/SqueezeMeta/bin:$PATH /home/nioo/sewuneta/.conda/envs/SqueezeMeta/SqueezeMeta/bin/DAS_Tool/DAS_Tool -i  -l  -c /home/nioo/sewuneta/sorghum_shotgun_metagenome_analysis/SqueezeMeta/sqmeta11/results/01.sqmeta11.fasta --write_bins 1 --score_threshold 0.25 --search_engine diamond -t 12 -o /home/nioo/sewuneta/sorghum_shotgun_metagenome_analysis/SqueezeMeta/sqmeta11/results/DAS/sqmeta11 --db_directory /home/nioo/sewuneta/sorghum_shotgun_metagenome_analysis/SqueezeMeta/db --debug at /home/nioo/sewuneta/.conda/envs/SqueezeMeta/SqueezeMeta/scripts/16.dastool.pl line 89.

**Comment by jtamames** [comment]
Hello
I don know exactly what you are wanting to do. If you are running concoct and putting it like Metabat, then why are you running Metabat afterwards
Anyway, the better solution is to update to 1.5 which already includes concoct.
Best,
J

**Comment by Sewunet-Abera** [comment]
Thanks Javier,
I selected maxbin, concoct and metabat2. But concoct is not running only the other two did. So what I thought was, let me keep maxbin running (almost a month now), and tread metabat2 for concoct. But if upgrading to 1.5 solves it all, I will do that. But a silly question I have is, will upgrading interferes with my current run? (I have been waiting it to complete almost three months now)

**Comment by jtamames** [comment]
But if you were able to select concoct is that you are already using 1.5. Can you check your version please?
Best,
J

**Comment by Sewunet-Abera** [comment]
The version is 1.4.
I picked the three binners based on the SqueezeMeta github page section 4 (-binners [string]: Comma-separated list with the binning programs to be used (available: maxbin, metabat, concoct) (Default: maxbin,metabat)). So went for all available ones.

**Comment by jtamames** [comment]
I think you have been reading the manual for version 1.5 while you have 1.4. Binning has been restructured in 1.5. Yes please, update to 1.5 (you can keep 1.4 if you want). Indeed your results will probably need some renaming, you can use the script versionchange.pl in the utils directory to make your data compatible with 1.5.
Best,
J

**Comment by Sewunet-Abera** [comment]
Thanks again Javier.
I will give it a try and get back to you.

**Comment by fpusan** [comment]
Closing due to lack of activity, feel free to reopen
