### ISSUE TITLE
Step 18 error related to checkm data setRoot

### ISSUE THREAD

**Issue by nebfold** [jtamames/SqueezeMeta#63]
I have SqueezeMeta installed on CentOS7 with conda. I've been trying to run the test data before using my own dataset, but I am running into a bug where step 18 hangs. I think I've tracked the bug down to `checkM data setRoot`:

The initial error:

```
[5 hours, 17 minutes, 40 seconds]: STEP18 -> CHECKING BINS: 18.checkM_batch.pl
  Creating /home/ben/test_squeeze/hadza/temp/checkm_batch
  Reading /home/ben/.conda/envs/SqueezeMeta/SqueezeMeta/data/alltaxlist.txt
  Looking for DASTool bins in /home/ben/test_squeeze/hadza/results/DAS/hadza_DASTool_bins
  23 bins found

  Bin 1/23: maxbin.045.fasta.contigs.fa.tax
  Using profile for domain rank : Bacteria

Error running command:    PATH=/home/ben/.conda/envs/SqueezeMeta/SqueezeMeta/bin:/home/ben/.conda/envs/SqueezeMeta/SqueezeMeta/bin/pplacer:/home/b
en/.conda/envs/SqueezeMeta/SqueezeMeta/bin/hmmer:$PATH /home/ben/.conda/envs/SqueezeMeta/SqueezeMeta/bin/checkm taxon_set domain Bacteria /home/be
n/test_squeeze/hadza/data/checkm_markers/Bacteria.ms > /dev/null 2>&1 at /home/ben/.conda/envs/SqueezeMeta/SqueezeMeta/scripts/18.checkM_batch.pl 
line 143.
Stopping in STEP18 -> 18.checkM_batch.pl
```

Running `/home/ben/.conda/envs/SqueezeMeta/SqueezeMeta/bin/checkm taxon_set domain Bacteria /home/ben/test_squeeze/hadza/data/checkm_markers/Bacteria.ms` manually:

```
It seems that the CheckM data folder has not been set yet or has been removed. Running: 'checkm data setRoot'.
Where should CheckM store it's data?
Please specify a location or type 'abort' to stop trying:

/data/shared_databases/squeezedb

*******************************************************************************
 [CheckM - data] Check for database updates. [setRoot]
*******************************************************************************


Path [/data/shared_databases/squeezedb] exists and you have permission to write to this folder.
(re) creating manifest file (please be patient).

Unexpected error: <class 'TypeError'>
Traceback (most recent call last):
  File "/home/ben/.conda/envs/SqueezeMeta/SqueezeMeta/bin/checkm", line 718, in <module>
    checkmParser.parseOptions(args)
  File "/home/ben/.conda/envs/SqueezeMeta/SqueezeMeta/bin/../lib/checkm/main.py", line 1229, in parseOptions
    self.updateCheckM_DB(options)
  File "/home/ben/.conda/envs/SqueezeMeta/SqueezeMeta/bin/../lib/checkm/main.py", line 82, in updateCheckM_DB
    DBM.runAction(options.action)
  File "/home/ben/.conda/envs/SqueezeMeta/SqueezeMeta/bin/../lib/checkm/checkmData.py", line 122, in runAction
    path = self.setRoot(path=action[1])
  File "/home/ben/.conda/envs/SqueezeMeta/SqueezeMeta/bin/../lib/checkm/checkmData.py", line 140, in setRoot
    path = self.confirmPath(path=path)
  File "/home/ben/.conda/envs/SqueezeMeta/SqueezeMeta/bin/../lib/checkm/checkmData.py", line 193, in confirmPath
File "/home/ben/.conda/envs/SqueezeMeta/SqueezeMeta/bin/../lib/checkm/manifestManager.py", line 85, in createManifest
    self.walk(parents, root_path, '', dirs, files, skipFile=manifestName)
  File "/home/ben/.conda/envs/SqueezeMeta/SqueezeMeta/bin/../lib/checkm/manifestManager.py", line 330, in walk
    self.hashfile(path),
  File "/home/ben/.conda/envs/SqueezeMeta/SqueezeMeta/bin/../lib/checkm/manifestManager.py", line 364, in hashfile
    hasher.update(buf)
TypeError: Unicode-objects must be encoded before hashing
```

Through trial and error I've found that I can manually set the data root to any empty directory. I only receive a TypeError if there are files inside the directory. 
 
Thanks for all of your hard work developing SqueezeMeta! :smiley:

**Comment by fpusan** [comment]
Hi!
CheckM data directory should be have been configured automatically while installing the databases.
What command did you use to install the databases and in what directory are they located?

**Comment by nebfold** [comment]
I do remember downloading the databases using the `download_databases.pl` but moved the database afterwards. I updated the configuration files but probably missed something. I will redownload them again to double check and let you know if this resolves the problem. Thanks!

**Comment by fpusan** [comment]
If you move the database, you have to run the `scripts/preparing_databases/configure_nodb.pl` script as if you were updating to a new version of SqueezeMeta (see section 11 in the ReadMe).

Basically, the make/download/configure database scripts will set up some hardcoded paths pointing to the location of the databases in your system.

**Comment by nebfold** [comment]
Redownloading the database fixed this issue. I managed to run the pipeline successfully with the test data. Thanks for your quick help!
