### ISSUE TITLE
Test run dies during assembly

### ISSUE THREAD

**Issue by ckeuschn** [jtamames/SqueezeMeta#90]
Hi, 
I installed SqueezeMeta via conda and run the test_install.pl with no errors. When I try a test run with the provided files it throws: 

> SqueezeMeta.pl -m coassembly -p Hadza -s test.samples -f raw -t 8
.
.
.

Running assembly with megahit
Error running command:    /Users/christoph.keuschnig/miniconda2/envs/SqueezeMeta/SqueezeMeta/bin/megahit/megahit  -1 /Users/christoph.keuschnig/Dropbox/ChBox/Work/TOTAL/MG_runs/Hadza/data/raw_fastq/par1.fastq.gz -2 /Users/christoph.keuschnig/Dropbox/ChBox/Work/TOTAL/MG_runs/Hadza/data/raw_fastq/par2.fastq.gz -t 8 -o /Users/christoph.keuschnig/Dropbox/ChBox/Work/TOTAL/MG_runs/Hadza/data/megahit >> /Users/christoph.keuschnig/Dropbox/ChBox/Work/TOTAL/MG_runs/Hadza/syslog 2>&1 at /Users/christoph.keuschnig/miniconda2/envs/SqueezeMeta/SqueezeMeta/scripts/01.run_assembly.pl line 106.
Stopping in STEP1 -> 01.run_assembly.pl (megahit)
Died at /Users/christoph.keuschnig/miniconda2/envs/SqueezeMeta/bin/SqueezeMeta.pl line 612.

and the syslog file ends with:

Traceback (most recent call last):
  File "/Users/christoph.keuschnig/miniconda2/envs/SqueezeMeta/SqueezeMeta/bin/megahit/megahit", line 1039, in <module>
    main()
  File "/Users/christoph.keuschnig/miniconda2/envs/SqueezeMeta/SqueezeMeta/bin/megahit/megahit", line 980, in main
    setup_logger()
  File "/Users/christoph.keuschnig/miniconda2/envs/SqueezeMeta/SqueezeMeta/bin/megahit/megahit", line 485, in setup_logger
    logger.info(software_info.megahit_version)
  File "/Users/christoph.keuschnig/miniconda2/envs/SqueezeMeta/SqueezeMeta/bin/megahit/megahit", line 149, in megahit_version
    return 'MEGAHIT %s' % check_output([self.megahit_core, 'dumpversion'])
  File "/Users/christoph.keuschnig/miniconda2/envs/SqueezeMeta/SqueezeMeta/bin/megahit/megahit", line 110, in check_output
    p = subprocess.Popen(cmd, stdout=subprocess.PIPE)
  File "/Users/christoph.keuschnig/miniconda2/envs/SqueezeMeta/lib/python3.6/subprocess.py", line 729, in __init__
    restore_signals, start_new_session)
  File "/Users/christoph.keuschnig/miniconda2/envs/SqueezeMeta/lib/python3.6/subprocess.py", line 1364, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
OSError: [Errno 8] Exec format error: '/Users/christoph.keuschnig/miniconda2/envs/SqueezeMeta/SqueezeMeta/bin/megahit/megahit_core'

is this saying that SqueezeMeta will not work on my mac OS?

Thanks for your help
Christoph

**Comment by fpusan** [comment]
No, sorry, SqueezeMeta only runs on Linux platforms

**Comment by jtamames** [comment]
Hello
As Fernando said, only Linux is supported. The reason for this is because many third-party software included (and needed) only run in Linux. Sorry about that.
Best,
Javier
