### ISSUE TITLE
ModuleNotFoundError: No module named 'tqdm' development version

### ISSUE THREAD

**Issue by fconstancias** [jtamames/SqueezeMeta#900]
Dear SqueezeMeta developers,

I have recently realized the development version offers the `--onlybins `option which I am interested in, [see](https://github.com/jtamames/SqueezeMeta/issues/899). Assembly and mapping are working fine but there is something wrong during. the 17.checkbins.pl step, see syslog [SQMdev.zip](https://github.com/user-attachments/files/17594098/SQMdev.zip). 

I have tried to install tqdm but it seems to be  already installed properly
```
(SqueezeMeta)$ pip install tqdm
Requirement already satisfied: tqdm in /home/ljc444/.conda/envs/SqueezeMeta/lib/python3.10/site-packages (4.66.1)
```

From the syslog it seems concoct was not run before the 17.checkbins.pl, only metabat2.

Any idea what is going on?

Many thanks!

**Comment by fconstancias** [comment]
When running test_install.pl, there is actually an issue with the checkm2 database. I actually just used the standard SqueezeMeta database I had already downloaded for the development version.

```
Checking that SqueezeMeta is properly configured... checking database in /maps/projects/hansen_ol-AUDIT/data/DB/SqueezeMeta/db
        nr.db OK
        CheckM manifest OK
CRITICAL ERROR: the /home/ljc444/.conda/envs/SqueezeMeta/SqueezeMeta/lib/checkm2/version/diamond_path.json points to the checkm2 database being located at /maps/projects/hansen_ol-AUDIT/data/DB/SqueezeMeta/db/uniref100.KO.1.dmnd, but we can't find it there, or it is corrupted

```

**Comment by fconstancias** [comment]
downloading the databases using the developpment version SqueezeMeta  didn't help. Nor downloading the CheckM2 database using checkM.

**Comment by fpusan** [comment]
- On CONCOCT not running, I suspect this is related to some problem in your environment with the dev version, since it ran successfully for you when using 1.6.4 in #899 . Let me know if you are using the `squeezemeta-dev` package from conda or just running the dev version on the environment provided by the `squeezemeta` package.

**Comment by fconstancias** [comment]
I installed the squeezemeta-dev using mamba using the following command `mamba create -n SqueezeMeta -c conda-forge -c bioconda -c anaconda -c fpusan squeezemeta-dev --no-channel-priority`.

Is it correct?

I already had an enrionment named `SqueezeMeta` and I assume it did overwrite it properly...

**Comment by fpusan** [comment]
Yes this should have worked. But the issue with tqdm surprises me a bit. Me and some collaborators have used the dev version in a few different computers and clusters and we've not experienced that.
Tqdm is included explicitly in the conda recipe so it should be present in your environment.
What's the output of `conda list | grep tqdm`?
I wonder if a python interpreter different than conda's could be being used to run CheckM2 (so the tqdm package is not available to it). I'll look into that.

**Comment by fconstancias** [comment]
Thanks!  Here is the output:
``` 
(SqueezeMeta) $ conda list | grep tqdm
tqdm                      4.66.1             pyhd8ed1ab_0    conda-forge
```

**Comment by fpusan** [comment]
And the output of `/usr/bin/env python -c "import tqdm"`?

**Comment by fconstancias** [comment]
This one didn't generate any output:

```
(SqueezeMeta) $ /usr/bin/env python -c "import tqdm"
(SqueezeMeta) $ 
```

**Comment by fpusan** [comment]
Then it means that the tqdm module is there and can be loaded

**Comment by fconstancias** [comment]
Thanks I will check my installation again !

**Comment by fconstancias** [comment]
I have installed the development version in a new conda environment: `mamba create -n SqueezeMeta-dev -c conda-forge -c bioconda -c anaconda -c fpusan squeezemeta-dev --no-channel-priority -y `

and running  test_install.pl generated some errors regarding python libraries - which was not the case when I installed squeezemeta-dev 'updating'  my squeezemeta v1.6.5 conda environment:

```
Checking that all the required python libraries are available in this environment

        python3 -h OK
        python3 -c 'import numpy' NOT OK
                Missing python library "numpy"
        python3 -c 'import scipy' NOT OK
                Missing python library "scipy"
        python3 -c 'import matplotlib' NOT OK
                Missing python library "matplotlib"
        python3 -c 'import dendropy' OK
        python3 -c 'import pysam' NOT OK
                Missing python library "pysam"
        python3 -c 'import Bio.Seq' OK
        python3 -c 'import pandas' NOT OK
                Missing python library "pandas"
        python3 -c 'import sklearn' NOT OK
                Missing python library "sklearn"
        python3 -c 'import nose' OK
...
```

```
WARNING: Some SqueezeMeta dependencies could not be found in your environment or failed to execute!
        - Missing python library "numpy"
        - Missing python library "scipy"
        - Missing python library "matplotlib"
        - Missing python library "pysam"
        - Missing python library "pandas"
        - Missing python library "sklearn"
```

```
which python
~/.conda/envs/SqueezeMeta-dev/bin/python

```
```
/usr/bin/env python -c "import scipy"
Traceback (most recent call last):
  File "/opt/software/anvio/7.1/lib/python3.9/site-packages/numpy/core/__init__.py", line 22, in <module>
    from . import multiarray
  File "/opt/software/anvio/7.1/lib/python3.9/site-packages/numpy/core/multiarray.py", line 12, in <module>
    from . import overrides
  File "/opt/software/anvio/7.1/lib/python3.9/site-packages/numpy/core/overrides.py", line 7, in <module>
    from numpy.core._multiarray_umath import (
ModuleNotFoundError: No module named 'numpy.core._multiarray_umath'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/opt/software/anvio/7.1/lib/python3.9/site-packages/scipy/__init__.py", line 67, in <module>
    from numpy import show_config as show_numpy_config
  File "/opt/software/anvio/7.1/lib/python3.9/site-packages/numpy/__init__.py", line 145, in <module>
    from . import core
  File "/opt/software/anvio/7.1/lib/python3.9/site-packages/numpy/core/__init__.py", line 48, in <module>
    raise ImportError(msg)
ImportError: 

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy C-extensions failed. This error can happen for
many reasons, often due to issues with your setup or how NumPy was
installed.

We have compiled some common reasons and troubleshooting tips at:

    https://numpy.org/devdocs/user/troubleshooting-importerror.html

Please note and check the following:

  * The Python version is: Python3.10 from "/home/ljc444/.conda/envs/SqueezeMeta-dev/bin/python"
  * The NumPy version is: "1.20.3"

and make sure that they are the versions you expect.
Please carefully study the documentation linked above for further help.

Original error was: No module named 'numpy.core._multiarray_umath'
/usr/bin/env python -c "import numpy"


```

I will check with the HPC staff.

**Comment by fpusan** [comment]
It looks like the environment wasn't activated?

**Comment by fconstancias** [comment]
Thanks for your reply! We should be doing other stuff on Saturday ...

It is.

```
[ljc444@esrumhead01fl ljc444]$ conda activate SqueezeMeta-dev
(SqueezeMeta-dev) [ljc444@esrumhead01fl ljc444]$ 
(SqueezeMeta-dev) [ljc444@esrumhead01fl ljc444]$ /usr/bin/env python -c "import scipy"
Traceback (most recent call last):
  File "/opt/software/anvio/7.1/lib/python3.9/site-packages/numpy/core/__init__.py", line 22, in <module>
    from . import multiarray
  File "/opt/software/anvio/7.1/lib/python3.9/site-packages/numpy/core/multiarray.py", line 12, in <module>
    from . import overrides
  File "/opt/software/anvio/7.1/lib/python3.9/site-packages/numpy/core/overrides.py", line 7, in <module>
    from numpy.core._multiarray_umath import (
ModuleNotFoundError: No module named 'numpy.core._multiarray_umath'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/opt/software/anvio/7.1/lib/python3.9/site-packages/scipy/__init__.py", line 67, in <module>
    from numpy import show_config as show_numpy_config
  File "/opt/software/anvio/7.1/lib/python3.9/site-packages/numpy/__init__.py", line 145, in <module>
    from . import core
  File "/opt/software/anvio/7.1/lib/python3.9/site-packages/numpy/core/__init__.py", line 48, in <module>
    raise ImportError(msg)
ImportError: 

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy C-extensions failed. This error can happen for
many reasons, often due to issues with your setup or how NumPy was
installed.

We have compiled some common reasons and troubleshooting tips at:

    https://numpy.org/devdocs/user/troubleshooting-importerror.html

Please note and check the following:

  * The Python version is: Python3.10 from "/home/ljc444/.conda/envs/SqueezeMeta-dev/bin/python"
  * The NumPy version is: "1.20.3"

and make sure that they are the versions you expect.
Please carefully study the documentation linked above for further help.

Original error was: No module named 'numpy.core._multiarray_umath'

```

**Comment by fpusan** [comment]
Weird, let's hear what your admins had to say. These modules are definitely
part of the conda environment and we'be tested the dev environment in a
couple computing clusters already...

**Comment by fconstancias** [comment]
Ok, I don't see the python libraries errors after a `module purge`. At least this makes sense... but still not sure about the "tqdm" module - when I initially run my script in the HPC I only activated the SQM conda env, no other modules loaded.

**Comment by fpusan** [comment]
Any updates from the admins?

**Comment by fconstancias** [comment]
Not yet unfortunately. I will keep you posted

**Comment by fpusan** [comment]
Closing due to lack of activity, feel free to reopen
